const routes = {
  home: '/',
  admin: '/admin',
  member: '/member',
  package: '/package',
  login: '/login',
  loginGoogle: '/login/google',
  register: '/register',
  logout: '/logout',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  shop: '/shop',
  cart: '/cart',
  orders: '/orders',
  about: '/about',
  error: '*',
  editPost: '/edit-post/:id',
  notFound: '/not-found',
  post: '/post',
  consult: '/consulting',
  news: '/news',
  koifish: '/koifish',
  manageOrder: '/manage-orders',
  managePost: '/manage-posts',
  manageUsers: '/manage-users',
  manageFish: '/manage-fish',
  managePonds: '/manage-ponds',
  manageNews: '/manage-news',
  approvePosts: '/approve-posts',
  dashboard: '/dashboard'
}

export default routes
